apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spesemese-pvc
  namespace: spesemese
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
